version: '3.1'

services:
  auth:
    restart: always
    build: ./auth
    depends_on:
      - database
    links:
      - database
    environment:
      USER_AUTH_SERVER_PORT: "0.0.0.0:1000"
      USER_AUTH_DB_PORT: "5432"

      USER_AUTH_JWT_EXPIRATION: 30

  database:
    image: postgres:alpine12
    container_name: postgres_database
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    ports:
    - "5432:5432"